services:
  backend:
    build: .
    container_name: backend-reservas
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://espitiaa3_db_user:TkJQVByR0BjIOlzi@almacenamiento.hg1ffyc.mongodb.net/base_datos_docu?appName=almacenamiento
      - PORT=3000
